name = "MolecularGraph"
uuid = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
authors = ["Seiji Matsuoka <ms0ae8ti1sj2ui@gmail.com"]
version = "0.17.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
coordgenlibs_jll = "f6050b86-aaaf-512f-8549-0afff1b4d57f"
libinchi_jll = "172afb32-8f1c-513b-968f-184fcd77af72"

[compat]
Cairo = "1"
Colors = "0.12"
DelimitedFiles = "1"
GeometryBasics = "0.4"
Graphs = "1"
JSON = "0.21"
MakieCore = "0.6, 0.7, 0.8"
Statistics = "1"
YAML = "0.4"
coordgenlibs_jll = "3.0.2"
julia = "1.6"
libinchi_jll = "1.5"
