name = "MolecularGraph"
uuid = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
version = "0.19.1"
authors = ["Seiji Matsuoka <ms0ae8ti1sj2ui@gmail.com"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RDKitMinimalLib = "44044271-7623-48dc-8250-42433c44e4b7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
coordgenlibs_jll = "f6050b86-aaaf-512f-8549-0afff1b4d57f"
libinchi_jll = "172afb32-8f1c-513b-968f-184fcd77af72"

[compat]
AbstractTrees = "0.4.5"
Base64 = "1"
Cairo = "1.1"
Colors = "0.13.1"
DelimitedFiles = "1"
GeometryBasics = "0.5"
Graphs = "1.12"
JSON = "0.21"
MakieCore = "0.9"
OrderedCollections = "1.8"
RDKitMinimalLib = "1.2.0"
Statistics = "1"
Test = "1"
YAML = "0.4"
coordgenlibs_jll = "3.0.2"
julia = "1.8"
libinchi_jll = "1.5"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging"]
